<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18202" started-at="2018-12-11T10:17:27Z" finished-at="2018-12-11T10:17:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18202" started-at="2018-12-11T10:17:27Z" finished-at="2018-12-11T10:17:46Z">
      <class name="webapplicationtest.FunctionalTest">
        <test-method status="PASS" signature="launch()[pri:0, instance:webapplicationtest.FunctionalTest@a67c67e]" name="launch" is-config="true" duration-ms="14247" started-at="2018-12-11T15:47:27Z" finished-at="2018-12-11T15:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="laodPages()[pri:0, instance:webapplicationtest.FunctionalTest@a67c67e]" name="laodPages" is-config="true" duration-ms="12" started-at="2018-12-11T15:47:42Z" finished-at="2018-12-11T15:47:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laodPages -->
        <test-method status="FAIL" signature="vehicleCheckMenuTest_001()[pri:0, instance:webapplicationtest.FunctionalTest@a67c67e]" name="vehicleCheckMenuTest_001" duration-ms="3667" started-at="2018-12-11T15:47:42Z" finished-at="2018-12-11T15:47:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [test2] but found [test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [test2] but found [test]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at webapplicationtest.FunctionalTest.vehicleCheckMenuTest_001(FunctionalTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleCheckMenuTest_001 -->
        <test-method status="PASS" signature="captureFailedTest(org.testng.ITestResult)[pri:0, instance:webapplicationtest.FunctionalTest@a67c67e]" name="captureFailedTest" is-config="true" duration-ms="159" started-at="2018-12-11T15:47:45Z" finished-at="2018-12-11T15:47:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=vehicleCheckMenuTest_001 status=FAILURE method=FunctionalTest.vehicleCheckMenuTest_001()[pri:0, instance:webapplicationtest.FunctionalTest@a67c67e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureFailedTest -->
        <test-method status="PASS" signature="crash()[pri:0, instance:webapplicationtest.FunctionalTest@a67c67e]" name="crash" is-config="true" duration-ms="108" started-at="2018-12-11T15:47:46Z" finished-at="2018-12-11T15:47:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- crash -->
      </class> <!-- webapplicationtest.FunctionalTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
